Svetlana
MariiaLuk/CRM_Team_Indus pull request #3
Opened 2023-03-01 15:40 UTC by SvetlanaSheremet

BasePage update

2023-03-01 19:43 UTC, MariiaLuk approved these changes
Great work creating method that will work with all menu options!

2023-03-02 00:34 UTC, Omid-Fallah requested changes

2023-03-02 00:34 UTC, Omid-Fallah commented on src/test/java/com/crm/pages/BasePage.java
Good job on your method but if you don't mind Can you please add locate each of your 4 elements individually so maybe we can call the directly with out using the method. thanks

2023-03-02 18:15 UTC, SvetlanaSheremet reviewed
Hello Omid! Thank you for your comment. I added my 4 WebElements in the Base page.

2023-03-02 21:36 UTC, redamalek1 approved these changes

2023-03-02 23:46 UTC, Omid-Fallah approved these changes

2023-03-03 00:15 UTC, merged